# Generated by Django 3.1.3 on 2020-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_store', '0004_auto_20201113_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='time_added',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_added',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='time_added',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
