# Generated by Django 3.1.3 on 2020-11-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_store', '0005_auto_20201115_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
