# Generated by Django 3.1.3 on 2020-11-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_store', '0006_auto_20201115_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='time_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='time_added',
            new_name='date_added',
        ),
    ]
