# Generated by Django 3.1.3 on 2020-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_store', '0007_auto_20201115_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=128)),
                ('sale_date', models.DateField()),
                ('price_cuts', models.CharField(max_length=128)),
            ],
        ),
    ]
